
- src: https://github.com/aloneroad/k8s-role-redis
  version: master
  name: redis

# - src: https://github.com/aloneroad/k8s-role-mysql
#   version: master
#   name: mysql

- src: https://github.com/aloneroad/k8s-role-memcached
  version: master
  name: memcached