- hosts: 127.0.0.1
  connection: local
  gather_facts: false
  run_once: true
  vars:
    redis_server_replicas: 3
    redis_sentinel_replicas: 3

    # mysql_root_password: foo
    # mysql_replication_password: bar
    # mysql_password: aaa

    memcached_replica_count: 1
  roles:
    - redis
    # - mysql
    - memcached